import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:geotagar/models/users.dart';
import 'package:flutter/material.dart';

import '../core/constants/constants.dart';
import '../core/constants/firebase_constants.dart';
//import 'package:geotagar/utils/methods.dart';

final userProvider = StateProvider<UserModel?>((ref) => null);

class AuthMethods {
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  //final _user = FirebaseFirestore.instance.collection('users');
  CollectionReference get _users =>
      _firestore.collection(FirebaseConstants.usersCollection);

  //
  // Future<model.UserModel> getUserDetails() async {
  //   User currentUser = _auth.currentUser!;
  //   Map snap = await FirebaseFirestore.instance
  //       .collection('users')
  //       .doc(currentUser.uid)
  //       .get();
  //   return model.UserModel.fromMap(snap);
  // }

  // Sign-up stuff
  Future signUp(
      {required String email,
      required String password,
      required String username,
      required String name,
      //required int age,
      String? gender,
      required String accountType}) async {
    String res = "Error signing up";
    try {
      UserCredential userCredential = await _auth
          .createUserWithEmailAndPassword(email: email, password: password);

      print(userCredential.user?.uid);
      await sendEmailVerification();
      // Add to database
      //_firestore.collection('users').doc(userCredential.user!.uid);

      UserModel userModel;

      if (userCredential.additionalUserInfo!.isNewUser) {
        userModel = UserModel(
          email: email,
          username: username,
          uid: userCredential.user!.uid,
          profilePicture: Constants.avatarDefault,
          banner: Constants.bannerDefault,
          awards: [],
          name: name,
          gender: gender!,
          accountType: accountType,
        );
        final docUser = _users.doc(userCredential.user!.uid);
        await docUser
            .set(userModel.toMap())
            .then((value) => print("$username added to FireStore."));
      } else {
        userModel = await getUserStream(userCredential.user!.uid).first;
      }

      // final data = {
      //   'email': email,
      //   'username': username,
      //   'uid': userCredential.user!.uid,
      //   'name': name,
      //   //'lastName': lastName,
      //   //'age': age,
      //   'gender': gender,
      //   'accountType': accountType,
      // };

      res = "Signed up successfully";

      User? firebaseUser = userCredential.user;
      return firebaseUser;

      // Code below was auto-generated by github copilot

    } on FirebaseAuthException catch (e) {
      if (e.code == 'weak-password') {
        print('The password provided is too weak.');
      } else if (e.code == 'email-already-in-use') {
        print('The account already exists for that email.');
      }
    } catch (err) {
      res = err.toString();
      //print(err);
    }
    return res;
  }

  Stream<UserModel> getUserStream(String uid) {
    return _users.doc(uid).snapshots().map(
        (event) => UserModel.fromMap(event.data() as Map<String, dynamic>));
  }

  Future<void> sendEmailVerification() async {
    User? user = _auth.currentUser;
    user!.sendEmailVerification();
    //showSnackBar(context, "Verification Mail")
    // ScaffoldMessenger.of(context!).showSnackBar(
    //     const SnackBar(content: Text("A Verification Email has been sent")));
  }

  Future logIn({
    required String email,
    required String password,
  }) async {
    try {
      UserCredential userCredential = await _auth.signInWithEmailAndPassword(
          email: email, password: password);
      User? firebaseUser = userCredential.user;
      return firebaseUser;
    } on FirebaseAuthException catch (e) {
      if (e.code == 'user-not-found') {
        print('No user found for that email.');
      } else if (e.code == 'wrong-password') {
        print('Wrong password provided for that user.');
      }
    }
  }

  Future signOut() async {
    try {
      return await _auth.signOut();
    } catch (err) {
      print(err.toString());
      return null;
    }
  }
}
