import 'package:flutter/material.dart';
import 'package:firebase_storage/firebase_storage.dart';


// Generated by github copilot

// class StorageMethods {
//   final FirebaseStorage _storage = FirebaseStorage.instance;

//   Future<String> uploadImageToStorage(
//       {required String filePath, required String uid}) async {
//     String res = "Error uploading image";
//     try {
//       final ref = _storage.ref().child('profileImages/$uid');
//       await ref.putFile(filePath);
//       res = "Image uploaded successfully";
//       return res;
//     } catch (err) {
//       print(err);
//       return res;
//     }
//   }
// }
