// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALmRTiDlxU1DGEuxtg0AcCuLpSA9d863I',
    appId: '1:765761477112:web:766d30d080583ff9db1e0d',
    messagingSenderId: '765761477112',
    projectId: 'geotagar-bb01a',
    authDomain: 'geotagar-bb01a.firebaseapp.com',
    storageBucket: 'geotagar-bb01a.appspot.com',
    measurementId: 'G-4E5F2NMP3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaoBmW3cJoEEql9fuFSvjPvwR8vxdb8Ps',
    appId: '1:765761477112:android:1c394a44984a2309db1e0d',
    messagingSenderId: '765761477112',
    projectId: 'geotagar-bb01a',
    storageBucket: 'geotagar-bb01a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNWxmrM0GimosKRPv1tYuH0CTrBqGZ7U8',
    appId: '1:765761477112:ios:9f101c94c31a5f36db1e0d',
    messagingSenderId: '765761477112',
    projectId: 'geotagar-bb01a',
    storageBucket: 'geotagar-bb01a.appspot.com',
    iosClientId: '765761477112-s4r0rkljdnr2lor5k9rg54avct6ren43.apps.googleusercontent.com',
    iosBundleId: 'com.example.geotagar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNWxmrM0GimosKRPv1tYuH0CTrBqGZ7U8',
    appId: '1:765761477112:ios:9f101c94c31a5f36db1e0d',
    messagingSenderId: '765761477112',
    projectId: 'geotagar-bb01a',
    storageBucket: 'geotagar-bb01a.appspot.com',
    iosClientId: '765761477112-s4r0rkljdnr2lor5k9rg54avct6ren43.apps.googleusercontent.com',
    iosBundleId: 'com.example.geotagar',
  );
}
