// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiwFKdthbm1nZ7XdZ2FPOe9kjAt_FoDts',
    appId: '1:310321124196:web:d47f93023b9e29bde52071',
    messagingSenderId: '310321124196',
    projectId: 'geotagar-d2d9d',
    authDomain: 'geotagar-d2d9d.firebaseapp.com',
    storageBucket: 'geotagar-d2d9d.appspot.com',
    measurementId: 'G-YQM768L8D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW-UyIFH9fRUjbVSZz2Mg6qRsd8-q64E8',
    appId: '1:310321124196:android:6220eccc09989090e52071',
    messagingSenderId: '310321124196',
    projectId: 'geotagar-d2d9d',
    storageBucket: 'geotagar-d2d9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBouyg0I0FVs_tl4VCyKw4zdlP3hkmd4Fw',
    appId: '1:310321124196:ios:39e6e128895fe6f4e52071',
    messagingSenderId: '310321124196',
    projectId: 'geotagar-d2d9d',
    storageBucket: 'geotagar-d2d9d.appspot.com',
    iosClientId: '310321124196-c8onnlv0d2qs1je97senjpjko08ievq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.geotagar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBouyg0I0FVs_tl4VCyKw4zdlP3hkmd4Fw',
    appId: '1:310321124196:ios:39e6e128895fe6f4e52071',
    messagingSenderId: '310321124196',
    projectId: 'geotagar-d2d9d',
    storageBucket: 'geotagar-d2d9d.appspot.com',
    iosClientId: '310321124196-c8onnlv0d2qs1je97senjpjko08ievq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.geotagar',
  );
}
